# Generated by Django 2.2.16 on 2022-11-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221110_1140'),
        ('reviews', '0002_auto_20221110_1306'),
    ]

    operations = [
    ]
