# Generated by Django 2.2.16 on 2022-11-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221102_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Slug категории'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Slug жанра'),
        ),
    ]
