# Generated by Django 2.2.16 on 2022-11-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221102_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='category',
        ),
        migrations.AddField(
            model_name='title',
            name='category',
            field=models.ManyToManyField(related_name='genres', to='reviews.Categories'),
        ),
    ]
