# Generated by Django 2.2.16 on 2022-11-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_merge_20221110_1347'),
        ('reviews', '0003_merge_20221110_1328'),
    ]

    operations = [
    ]
